### ISSUE TITLE
responsive layout 

### ISSUE THREAD

**Issue by elhe26** [Stacked-Org/stacked#1]
Is this package a combination of responsive_builder and provider architecture packages (best of both worlds)?
Does this package support responsive layouts out of the box (different phone sizes)?

Awesome package. Thanks!!

**Comment by FilledStacks** [comment]
Hi @elhe26 this is not a combination of those package. It's an upgraded version of provider_architecture. I wanted to get away from the Provider naming and add reactive functionality to the viewmodel / service relationship.

The package allows for the responsive_builder to be used to it's full potential, the same as Provider Architecture does. I didn't combine the repo's because responsive builder is a UI implementation patter, it's not apart of the architecture. It's basically just an implementation detail in your overall app. The same as how you would implement your own routing.
