### ISSUE TITLE
[Question] Using DialogService with options

### ISSUE THREAD

**Issue by eimlav** [Stacked-Org/stacked#100]
I am trying to use the DialogService to create a custom dialog ui for either displaying a message or for providing the user with a series of options to choose from (such as using `actions` in an AlertDialog) . 

Currently I am just using `mainButtonTitle` and `secondaryButtonTitle` to workaround this. I have found that the DialogRequest contains `takesInput` and `customData` but I can't figure out how these are actually supposed to be used. 

Can anyone show me an example of this? Cheers.

**Comment by FilledStacks** [comment]
Any of the properties you include when calling `showCustomDialog` will be available on the `DialogRequest` for the registered builder. These properties are used how you want them to be used. You can do a switch statement and return different dialogs based on your dialog request. 

if you're passing takes input you'll probably check that and show input fields in your dialog to take the input? There's no specific example because it's just a bunch of if statementes. I pass my custom data as an enum for different dialog types then i have a switch statement for that customData property that returns a different dialog based on the case. 

```dart
switch(customData) {
  case DialogType.Basic:
    return Dialog(...);
  case DialogType.BasicImage:
   return Dialog(...);
  case DialogType.BasicImageSvg:
   return Dialog(...);
  ...
}
```

In another implementation most of the dialogs look the same with a button hiding or the description hiding. In that case I simply check if the property on dialogRequest is there and then hide or show the dialog. 

Another implementation i also pass a class to the custom data which has properties on it specifically for my dialog which I then use to build the UI based on properties on that object.

Those are 2 solutions you can use now, whichever one would work for you, there's also hundreds of other ways because it's basically an if check you have to do. If your condition is satisfied you build the dialog you want and return that. If you have any specific problems you can mentions them. I probably won't give you the exact source code but you should be able to figure it out from pseudo code.

**Comment by eimlav** [comment]
Hi @FilledStacks thanks for detailed reply. This makes perfect sense now. I've been able to apply what you've explained to set up the different dialogs. Thanks!
