### ISSUE TITLE
[bug]: Can't delete bottom sheet

### ISSUE THREAD

**Issue by mohammedabdelkhalik** [Stacked-Org/stacked#1008]
### Describe the bug

when i try to delete bottom sheet there is no subcommands for bottom sheet

### To reproduce

`stacked delete bottom_sheet YOUR_BOTTOM_SHEET`

### Screenshots

![2023-07-30 at 5 16 PM](https://github.com/Stacked-Org/stacked/assets/135126694/396a6b38-730d-4b3a-88ca-75919ea5f4b9)

**Comment by ferrarafer** [comment]
Hi @mohammedabdelkhalik , that feature does not exists on Stacked CLI. The `delete dialog` command was introduced by @sebastianbuechler on [this](https://github.com/Stacked-Org/cli/pull/34) PR. If you can, you are welcome to implement `delete sheet` command and make a pull request, after passing the reviews will be merged into `stacked_cli`. Otherwise, we will add it sooner or later. At the moment we are busy with other priorities but I will add this feature request to the backlog.

Cheers!

**Comment by zilliw** [comment]
Any news about this improvement? I've got the same problem in my project

Thanks for you reply !

**Comment by sebastianbuechler** [comment]
> Any news about this improvement? I've got the same problem in my project
> 
> Thanks for you reply !

You can simply build it yourself similar to the `delete dialog` functionality: https://github.com/Stacked-Org/cli/pull/34
