### ISSUE TITLE
Best practices with Firestore and possibly a feature request

### ISSUE THREAD

**Issue by scullabyte** [Stacked-Org/stacked#102]
I have tried to optimize stacked to easily fit into Firestore by adding some common data types and methods around stacked's `MultipleStreamsViewModel`. I would like your opinion on whether this is the best approach. Ultimately, I think it would be cool to have a firestore branch of stacked services and I'd be happy to help write that code. 

First, there are 4 common data types in firestore that I think almost all apps fall under:

```dart
enum FirestoreModelType {
  CollectionModel,
  // publicly accessible collection
  // i.e. 'articles'
  DocumentModel,
  // publicly accessible document
  // i.e. global app settings '/settings/global'
  UserCollectionModel,
  // collection accessible to a user based on a uid
  // i.e. todos where "uid" == $uid
  UserDocumentModel,
  // document accessible to a user based on a uid
  // i.e. settings '/settings/$uid'
}
```

Two of the four types require a uid first, So I'm leveraging firebaseAuth's `onAuthStateChanged` stream and combining it with RXDart's `switchMap`. Here's how I'm listening to these 4 different data types:

```dart
class UserData<T> {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final String collection;

  UserData({this.collection});

  Stream<T> get documentStream {
    return _auth.onAuthStateChanged.switchMap((user) {
      if (user != null) {
        Document<T> doc = Document<T>(path: '$collection/${user.uid}');
        return doc.streamData();
      } else {
        return Stream<T>.value(null);
      }
    });
  }

  Stream<List<T>> get collectionStream {
    return _auth.onAuthStateChanged.switchMap((user) {
      if (user != null) {
        List<CollectionValue> _collectionValues = [
          CollectionValue(key: "uid", value: user.uid)
        ];
        CollectionWhere<T> doc = CollectionWhere<T>(
          path: '$collection',
          collectionValues: _collectionValues,
        );
        return doc.streamQuery();
      } else {
        return Stream<List<T>>.value(null);
      }
    });
  }
```

So the `MultipleStreamsViewModel` would have something like:

```dart
  Map<String, StreamData> get streamsMap => {
    todosStreamKey: StreamData(
    	UserData<List<Todo>>(collection: 'todos').collectionStream),
    settingsStreamKey:	StreamData(
		UserData<Settings>(collection: 'settings').documentStream),
    ),
  }
```

Let me know if you see any flaws in this architecture design. Is there something wrong with calling `onAuthStateChanged` to open every user-based stream? I know that in your example apps you've passed the uid down to the viewmodel, so I figured another way to do this effectively would be to attach a RXValue for uid to the authentication service and using get_it to hold that id in the models above.

**Comment by FilledStacks** [comment]
That's pretty nice. I haven't built anything around generic firestore interaction through a service. The functions are usually repeated in my project. I don't see anything wrong with your implementation right off the bat. I don't understand or know of the pattern used for the UserData class so it's a bit confusing but it looks like a great pattern. Is there a name for it? I have a habbit to solve problems with the bear bones OO paradigms and tend to ignore newer, lots of the time, better patterns. 

I haven't delved into generalsing any of our 6 implementations for firebase documents but I have a large sample set of what's required so I do have the data to create something that will work in all 6 cases. I don't have the time for it at the moment but it's something that I'm definitely going to do.

**Comment by scullabyte** [comment]
I got the idea from Fireship about a year ago. Here's the original code:
https://github.com/fireship-io/flutter-firebase-quizapp-course/blob/master/lib/services/db.dart

You'll see in the Document and Collection classes he's passing in the models as the generics:

```dart
	// This is inside class Collection<T> where T is the Model
  Stream<List<T>> streamData() {
    return ref.snapshots().map((list) => list.documents.map((doc) => Global.models[T](doc.data) as T) );
  }
```

and then he has a Global class which has this code:
```dart

    // Data Models
  static final Map models = {
    Topic: (data) => Topic.fromMap(data),
    Quiz: (data) => Quiz.fromMap(data),
    Report: (data) => Report.fromMap(data),
  };
```

It seems complicated but its just a lot of shorthand really. I modified it to allow for queries by creating the `CollectionWhere` class. 

This whole approach depends on listening to `onAuthStateChanged` for each one of your viewModel streams before it combines it with the firestore model you're getting. I know doing something like using `RxValue` to store the uid in the auth service is more straightforward and maybe less expensive? Idk if thats negligible. Poke holes in this approach if you can see them please.

There are a lot of gaps in my knowledge about architecture to see the flaws here. I have this approach combined with `MultipleStreamsViewModel` working on one app I've built and its a pretty smooth process to just put together a model and add it into a stream with none of the boilerplate, but I'm sure there might be some tradeoffs I'm missing.

**Comment by FilledStacks** [comment]
I remember that approach in his code. I read through that repo as well to see how he was handling firebase collections and I remember liking it. 

There's no problems that I can see at the moment, if it's a great setup for you then it's doing its job. I think it only appears complicated because you can see the implementation of the Class Collection<T> but it's not that complicated. If that was in a package then it would look a lot cleaner when using it. 

I don't see any problems with it, especially not performance. I prefer guarding against functions before even getting there instead of checking the authState for every subscription but that "check" is also not expensive so both ways work out the same. This is probably the closest thing to a good generic approach that I've seen. I've been lazy when it comes to firestore because it's so easy to use I haven't been bothered by re-writing some code in a new code base. I'll definitely spend some time looking into a generic approach, it will most likely only be after I'm done with the current series. Which has 3 videos left in it. 

So that's a month or two from now. things move slow when there's so many commitments.

**Comment by FilledStacks** [comment]
**FilledStacks Team:** We have built multiple firebase services. Go through all the implementations  and create a stacked_firebase package where we generalise the functionality to take into account all our implementations and release those as a separate package. 

We have in iLay-bye the authentication for mobile number, google, email, facebook which we can wrap into a `FirebaseAuthenticationService` since most devs struggle with the mobile number authentication implementation I think our solution would help them out greatly.
