### ISSUE TITLE
[Feature Request] Create Bottom Sheet Service

### ISSUE THREAD

**Issue by SeanningTatum** [Stacked-Org/stacked#103]
Just like in react native, a programatic bottom sheet would be nice for flutter.

**Comment by FilledStacks** [comment]
@SeanningTatum bottom sheet is very custom usually, there's no default way it should look so it's not something I've been able to re-use in different projects. if it needs t be controlled i do that from the ui. in my bottom sheet video i show you how to control it programatically.

**Comment by saileshbro** [comment]
Yes I was about to request this feature, It would be nice if there was something like bottom sheet service, where we could register a custom bottomsheet.

**Comment by JayPerfetto** [comment]
I use https://github.com/jamesblasco/modal_bottom_sheet in my Stacked architecture app, but it definitely requires some customization. Typically, I don't use the navigation service at all to throw a CupertinoBottomSheetModal, I just await the result from inside a model function. 

Also, in order to get the Cupertino style "back-drop" layering, you have to override some of the generated values in the generated Router file, since Auto-Route doesn't have a handler built in for MaterialWithModalsPageRoute -> eg:
 return MaterialWithModalsPageRoute<dynamic>(
        builder: (context) => HomeView(key: args.key),
        settings: data,
      );

**Comment by FilledStacks** [comment]
@JayPerfetto that's what I also use for my bottom sheet functionality. It'll be hard turning that into a service that's a general use case but I'll combine all the ways I build things and I'll see if I can get that working.

**Comment by FilledStacks** [comment]
I'm leaning more and more to implementing something like this given I'm still showing most of my bottom sheets from the UI which sometimes, only sometimes, is not what I want. Will tag this with enhancement and work on this after the theme manager.

**Comment by FilledStacks** [comment]
Bottom sheet service has been created and is available along with [this video](https://youtu.be/OvBl-j59bOg)
