### ISSUE TITLE
[feature]: FormView toggle / checkbox fields

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Stacked-Org/stacked#1083]
### Is your feature request related to a problem? Please describe.

Currently FormView only has Text, Date, Dropdown.
Is there any planned support for other types like Toggle / Checkbox, Dropdown with search, Radio, Multiselect

Instead of reinventing the wheel, can Stacked work with other components from ecosystem like
1. [flutter_form_builder](https://pub.dev/packages/flutter_form_builder)
2. [dropdown_search](https://pub.dev/packages/dropdown_search)
3. [multi_select_flutter](https://pub.dev/packages/multi_select_flutter)

These are just recommendations.

### Describe the solution you would like

FormView to have other required form fields ether developed internally or work with other popular packages

**Comment by FilledStacks** [comment]
Hi, no.

At the moment there is no plans to support text editing. 

We're not trying to reivent the wheel, instead we want to do the exact opposite. We built it so that it's usable with every single form building out there. 

We ONLY sync values between the textController and the ViewModel, we don't do anything else. 

So you can use that text controller with literally any package that you like, we just make sure the text data is available in the ViewModel when needed. No UI functionality will be added to Stacked's form functionality.
