### ISSUE TITLE
[bug]: Support to get_it 8.0.0

### ISSUE THREAD

**Issue by JgomesAT** [Stacked-Org/stacked#1135]
### Describe the bug

Project can't be  compile due to dependencies

Because stacked 3.4.3 depends on get_it ^7.1.4 and no versions of stacked match >3.4.3 <4.0.0, stacked ^3.4.3 requires get_it ^7.1.4.
So, because my_andorra_telecom depends on both stacked ^3.4.3 and get_it ^8.0.0, version solving failed.

### What operating system do you use?

macOS

### Steps to reproduce the issue

Run Flutter pub get

**Comment by JgomesAT** [comment]
any news?

**Comment by Pebkac03** [comment]
There is a PR by the Renovate bot to bump get_it to ^8.0.0 which fails due to unrelated flutter analyze non-breaking unnecessary null check warnings

I am working on a PR for #1145 which should, among other things, stop Renovate from being blocked.

You should be able to, in the meantime, fork Stacked and bump to 8.0.0 yourself. See [here](https://medium.com/@ayalon.idan/getit-v8-migration-examples-24344ed1a130) for a migration guide should it be needed.

**Comment by FilledStacks** [comment]
I'll merge that one in now. 

Thanks for the patience @JgomesAT

**Comment by FilledStacks** [comment]
I removes the linting for now since I haven't spent time updating the codebase to the new Flutter linting rules so as long as the tests pass that we have setup the renovate bot will auto update the packages going forward.
