### ISSUE TITLE
Inject other services without Get_It

### ISSUE THREAD

**Issue by Melak12** [Stacked-Org/stacked#119]
I have base services such as DatabaseService that are possibly consumed in every ViewModels. How can I inject these services without using get_it package? Is ProxyProvider good enough?

**Comment by alvinvin00** [comment]
you can, but personally i wouldn't do it because that could be cumbersome later. Mind asking why you don't want to use get_it?

**Comment by Melak12** [comment]
Provider by itself is state management and DI tool so I don't see the point to use another third party plugin. I have made my base_vm that extends BaseViewModel. Let me know if there is wrong with the following approach: 

`class BaseVM extends BaseViewModel {
  final BuildContext context;
  
  /// Common Providers
  DatabaseService dbService;
  
  BaseVM({@required this.context}) {
    dbService = Provider.of<DatabaseService>(context, listen: false);
  }
  
}`

**Comment by FilledStacks** [comment]
@Melak12 using provider is perfectly fine. To give you some context. The only reason i use get_it is because it's easier to read and to teach, and easier to understand when just looking at the code. This goes for the viewmodels where it's used as well as the setup of it. These are very important factors if the code you're writing will be handed over to a new team when you're done with it. Which is about 80% of our client projects. I focus on readability and maintainability for code that will be maintained for years, 5 or more. So as new developers come in and off the project having a more readable code base speeds up the onboarding process tremendously over that amount of time.

**Comment by alvinvin00** [comment]
to me, this looks usable, as long as you achieve the goal, nothing is wrong ☺

**Comment by Melak12** [comment]
Thanks, @alvinvin00  and @FilledStacks. I will stick with the provider approach with my base model that extends Stacks' BaseViewModel.
