### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by elhe26** [Stacked-Org/stacked#12]
Hi,

I was checking the documentation and there's an error on BaseViewModel example:

```dart
class WidgetOne extends StatelessWidget {
  ...
          // A bit silly to pass the same property back into the viewmodel
          // but here it makes sense
          child: model.busy(model.currentHuman) // This return true if we have the model
              ? Center(
                  child: CircularProgressIndicator(),
                )
              : Container(/* Human Details styling */)
        ),
      ),
    );
  }
}
```
It should be this:

```dart
class WidgetOne extends StatelessWidget {
  ...
          // A bit silly to pass the same property back into the viewmodel
          // but here it makes sense
          child: model.busy(model.currentHuman) // This return true if we have the model
              ? Container(/* Human Details styling */)
              :  Center(
                  child: CircularProgressIndicator(),
                )
        ),
      ),
    );
  }
}
```

This is based on the BaseViewModel implementation:

```dart
Map<int, bool> _busyStates = Map<int, bool>();

  /// Returns the busy status for an object if it exists. Returns false if not present
  bool busy(Object object) => _busyStates[object.hashCode] ?? false;
```

Regards,

**Comment by FilledStacks** [comment]
Hi, that's incorrect. 

The code reads as follows. "If the currentHuman property is marked as busy show the busy indicator, else display its details". You're suggesting the complete opposite which is wrong. 

If setBusy was not called with model.currentHuman then it will be false because the hashcode for currentHuman is not in there. So when it's busy we show the busy indicator when it's not we show the human details. But besides the technical details. The example shows how to check if something is busy, regardless of if it's busy or not.
