### ISSUE TITLE
How to perform *some* reactive actions on a non-reactive view/VM

### ISSUE THREAD

**Issue by JayPerfetto** [Stacked-Org/stacked#129]
Hi FilledStacks - I have a full screen GoogleMap widget in my app that is in a non-reactive view + Multiple Streams view model. I had to choose non-reactive because I am using compass + user location streams which would cause the map to continuously rebuild + flash / flicker any time my streams got data (all the time).

I have gotten around all of my non-reactive limitations by using reactive services to manage things like map markers, camera animations, etc, and that is all working great such that the elements *within* my map update reactively but the map widget itself does not rebuild.

*Here is my issue* - I need to resize the map widget programatically to do a split view, where on the tap of a FAB, the map widget animates from full screen to half screen, and a separate list view widget will fill this space. 

*I do not want to use a bottom sheet for this UI interaction* - can anyone help me to understand how I would perform this animation smoothly without triggering rebuilds / flickering of the Map?

View:
```
import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';

import '../../../../../app/locator.dart';
import '../main_map/explore_viewmodel.dart';

class ExploreView extends StatelessWidget {
  ExploreView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<ExploreViewModel>.nonReactive(
        viewModelBuilder: () => locator<ExploreViewModel>(),
        disposeViewModel: false,
        fireOnModelReadyOnce: true,
        onModelReady: (model) async {
          model.init();
        },
        builder: (context, model, child) {
          double height = MediaQuery.of(context).size.height;
          if (model.splitViewActive) height = height * 0.5;

          return Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.transparent,
              elevation: 0.0,
              brightness: MediaQuery.platformBrightnessOf(context),
            ),
            key: GlobalKey<ScaffoldState>(),
            extendBodyBehindAppBar: true,
            body: AnimatedContainer( // split view, animated container, stack, not sure what this needs to be!
              duration: Duration(
                milliseconds: 500,
              ),
              height: height,
              child: FullScreenGoogleMap(), // this is a ViewModelWidget<ExploreViewModel>
            ),
            floatingActionButton: FloatingActionButton(
              backgroundColor: Theme.of(context).colorScheme.onSurface,
              foregroundColor: Theme.of(context).colorScheme.surface,
              mini: false,
              onPressed: () {
                model.setSplitViewActive(!model.splitViewActive);
              },
              tooltip: 'Show Details',
              child: Icon(Icons.details),
            ),
          );
        });
  }
}

```

**Comment by FilledStacks** [comment]
There are 2 things i would consider doing.

1.  **Use a static child**: This is the way that flutter does things usuallly. Most of the widgets that require a lot of rebuilds like a list view for instance has a property called child that you can construct once and it'll be provided to the builder function for you to use. `ViewModelBuilder` has a `staticChild` property where you can construct your map. And then make use of it in the builder (the last parameter).

2. **Use a stream builder**: Since a non reactive ViewModelBuilder is basically a stateless widget that has access to a viewmodel you can use built in state management methods from flutter. StreamBuilder works the best for this. Use a stream builder that returns your map at a certain size for a certain event. and a different size for a different event. You can then basically control it to your will based on adding values onto the stream in your viewmodel.

**Comment by JayPerfetto** [comment]
That first approach is fascinating, and could very well be the missing piece to the puzzle here - ill give it a shot and report back my results - thanks again good sir
