### ISSUE TITLE
onModelReady function on the initial view is called every time I refresh my web app in Flutter Web

### ISSUE THREAD

**Issue by xcsob** [Stacked-Org/stacked#142]
Hello,  
I'm using Flutter Web to create a web app. 

I don't know if this is intended, but whatever I refresh my web app or I type a link in my browser, the function that I call on the onModelReady inside my initial route page is called. 

Is this an intended behaviour?

Another question regarding the onModelReady is the following: does the widget inside a view builds only after the onModelReady function is completed? In another page (not the initial route), I've an async function that fetch some data from firebase and I implemented an async onModelReadyFunction. 
I implemented something like we see in this video, for the fetchPosts: 
youtube.com/watch?v=kDEflMYTFlk&feature=youtu.be

Is this the right way to implement this, or do I need to use FutureViewModel?

**Comment by FilledStacks** [comment]
On web that would most likely happen because the ViewModel is being rebuilt so everything starts from scratch. 

yes, the builder is only fired after onModelReady is called but onModelReady is not awaited on so it'll call it and then move on to the next function which is initialisation of "special viewmodels" like Future, Stream and Reactive viewmodel.

**Comment by xcsob** [comment]
Thank you for your answer. 

Since in your video you shown that we can call onModelReady with an await, also this will not wait for the function to be completed? 

So my understanding is that whenever we want to build a page that needs to wait for some data from a future, we should use Future view builder, right?

**Comment by FilledStacks** [comment]
@boscux "should" is not the right word. Future ViewModel reduces this code.

```dart
dynamic data;

Future initialise() async {
setBusy(true);
data = await myFuture();
setBusy(false);
notifyListeners();
}
```

to 

```dart
futureToRun() => myFuture();
```

Everything returned by the future is stored in the data property. 

You don't need to await for onModelReady to complete since we have futures. It's there to call something as soon as the model is ready. Usually an async function. Fetching posts, setting the view to busy, showing the user a loading indication, and then showing the data when it comes back.

**Comment by xcsob** [comment]
Thank you so much, now everything is clear. 
I'm going to use it!
