### ISSUE TITLE
Multiple Provider

### ISSUE THREAD

**Issue by duynghiatran** [Stacked-Org/stacked#145]
Hi, what is the way to have multiple ViewModel providers for a widget?

**Comment by FilledStacks** [comment]
Hi, there is by that won't make sense since a ViewModel is the Model for that specific view. It's not like BLoC where the BLoC contains features or state to be used by other views. It's the Model specifically for that view. Meaning it store information specific to that view. Whether it's busy, the information to show in that view, if  you're showing a certain button or not. 

If you want to share data you put it in a service and use it in all the viewmodels you want to access it in.

**Comment by duynghiatran** [comment]
In my application, I have a General Condition screen that needs to be shown when the user click on a button. I would like to let the sign in page to consume the two models: `SignUpViewModel `and the `GeneralConditionViewModel`. I don't want to group these two VM as they are for different concern and I can reuse the `GeneralConditionViewModel `somewhere else. What would be best to do?

I would also want to know more about your comment on BLoC. You said that BLoC containes feature or state, isn't the VM the same? I mean the VM is responsible for communicating with repositories but it also stores state and is triggers actions.
For example, in my `SignUpViewModel`, I have 
attributes corresponding to every fields in my form like 
```firstName, lastName, password, email``` 
and also states 
```showError, isSubmitting```
and actions
```submitPressed(), clearPressed()```

Please correct me if this architecture is not appropriate, I would like to know your opinion.
Thanks.

**Comment by Rayv1** [comment]
@tdnghia98 when i have functionallity which i need on more than one VM, i create a Service which contains it. Maybe you could provide more infos about your General Condition Screen. Whats the reason for it? What do you want to show or what is it doing?

**Comment by duynghiatran** [comment]
@Rayv1 so say I have 
- a link in the sign up screen that displays a Widget containing General Conditions. (GC)
- a link in the profile screen that displays this Widget.
- a link in the sign in that displays this Widget.

I need to consume the General Condition VM in these screens but I surely also need the VM dedicated to the View itself.
Say I have a repository for the GC , a sign up service that does the sign up, that means if I only provide one VM for each View I will always have to repeat the logic to fetch data from the GC repository?

**Comment by FilledStacks** [comment]
@tdnghia98 VM's does contains state. That's why it exists. The comment was "It's not like BLoC where the BLoC contains features or state to be used by other views" Which means 1 bloc is used in multiple views meaning a change to the bloc has to be retested for all those views.

What you want to do requires a service. Create a new service that does what you need and use it in both viewmodels, but you definitely don't need two use other viewmodels in another views viewmodel. What the services video on my channel to see how to use services.

**Comment by duynghiatran** [comment]
Sure, I will try to optimize as you said. Thanks!
