### ISSUE TITLE
More devs

### ISSUE THREAD

**Issue by BeeLabs** [Stacked-Org/stacked#15]
Stacked seems very interesting, as it answers many of the architecture decisions a developer needs to make.  Nice work @FilledStacks 

As people start adopting this package, you will need help debugging the issues that arise, and implement new features. You will also need a technical writer, and give Stacked a website of its own.

Early adopters will test any new idea. But if you want to give this package a serious adoption rate, you need to get more devs on your team.  I have seen how small teams have stifled projects. I makes sense to find a trusted second man for the project and its Github account.

**Comment by FilledStacks** [comment]
Thanks for the concern @BeeLabs I do have 5 developers in the filledstacks team and 2 designers :) As we develop client apps we will be developing this package at the same time since it's being built specifically to improve our app development capabilities in Flutter. 

I'm in no rush with the project in terms of adoption currently. There's a few other basics that I'd like to add which I'm still thinking about.
