### ISSUE TITLE
[Stacked Themes] saving the theme state doesn't work

### ISSUE THREAD

**Issue by ajnaf** [Stacked-Org/stacked#152]
When the app launches it is always on system mode .

**Comment by FilledStacks** [comment]
@ajnaf at the moment it will only save the theme if the default theme is not system. That's how it''s been implemented now. I have to still update the package to save any last themeMode set which I will implement with the functionality to swap between system and light / dart. 

The reason it does that when default is system is because system should always return what the user wants.

**Comment by ajnaf** [comment]
The problem is no matter what i choose it always takes the system and if the device doesn't support the default is light theme

**Comment by FilledStacks** [comment]
@ajnaf try 0.1.0+1

**Comment by ajnaf** [comment]
when i call the toggleDarkLightTheme method it starts the app again

**Comment by ajnaf** [comment]
works thank you
