### ISSUE TITLE
Using the view model widget in the Modal Bottom Sheet

### ISSUE THREAD

**Issue by Melak12** [Stacked-Org/stacked#169]
I am trying to use the existing View Model into Modal Bottom Sheet but it throws error of the view model is not accessable in the bottom sheet scope since it uses its own context. How can I achieve this?

**Comment by FilledStacks** [comment]
A bottom sheet should be treated like a completely new view, because it is a new view pushed onto the navigator. Each view should have its own viewmodel. ViewModels should not know about other viewmodels, they would never need to. 

If you really want to do it, which I don't recommend, you can simply pass it to the sheet when you construct it.

**Comment by JayPerfetto** [comment]
Agreed with FilledStacks here - I use modal bottom sheet quite a lot in my app and the approach for this should be to abstract any shared functionality / values into a reactive service and use that in both viewmodels
