### ISSUE TITLE
Using nonReactive constructor doesn't dispose the viewmodel associated

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#171]
When using the nonReactive constructor the ViewModel is not disposed because of the `Provider.value` constructor being used. This issue is to ensure we find a way to still dispose the viewmodel when the value constructor is used.

**Comment by JayPerfetto** [comment]
Would this cause any streams to be left hanging in these viemodels? What is the implication on the disposal of any streams in a MultipleStream Nonreactive VM?

**Comment by FilledStacks** [comment]
@JayPerfetto I actually haven't seen the bug but it was reported to me on the slack. The stream was still firing after leaving the screen. This would definitely cause hanging streams which is not great. If this is a bug it's a nasty one, not experienced by many since the recommended way for using a StreamViewModel is with a reactive constructor. Given you want your UI to rebuild as the values come in. 

But in this there actually was a use case for it to not rebuild so the nonReactive constructor works. I have someone that will take a look at it soon and see if it's happening and fix it if it does. Should be in the next day or two, I think.

**Comment by JayPerfetto** [comment]
My main use case for a non reactive viewmodel is with Google Maps - I've been using Stacked now since mid summer, and have tried everything i could throw at it, but non-reactive VM seems to be the only answer for the following reason:

I am using multiple streams VM to expose a stream of the users current location, the authenticated user, the device's compass bearing, and a stream of location data to display on the map from Firestore.

When all of those stream events fire, if the View is reactive, the google map rebuilds every time causing flickering and an unusable map. My solution has been to have this view be non-reactive, and effectively just push any shared reactive data into reactive service classes and manually calling notify listeners when I know it needs to be called.

Do you have any best practices around using GoogleMaps with Stacked that I might be ignorant to? Since I saw this issue my ears def perked up because I have 100% seen print statements from my streams' onData callbacks firing after I leave that screen which was always somewhat concerning

**Comment by aicodechef** [comment]
I was able to create the following test case to isolate this issue. I believe this is the first step in resolving the defect. The last few lines of the test case may need to be adjusted a bit. I feel like this should enable the quickest, most pain free route to resolving the defect and testing it.

```dart
testWidgets(
    'Using ViewModelBuilder.nonReactive CNTR the builder method should NOT run after the model is disposed.',
    (WidgetTester tester) async {
  final stateKey = GlobalKey<State<ViewModelBuilder<TestViewModel>>>();
  int buildCounter = 0;
  var testViewModel = TestViewModel();
  var widget =
      buildTestableWidget(ViewModelBuilder<TestViewModel>.nonReactive(
    builder: (context, model, child) {
      return Container();
    },
    viewModelBuilder: () {
      buildCounter++;
      return testViewModel;
    },
    key: stateKey,
  ));
  await tester.pumpWidget(widget);
  stateKey.currentState.dispose();
  await tester.pumpWidget(widget);
  stateKey.currentState.reassemble();
  await tester.pumpWidget(widget);
  stateKey.currentState.initState();
  await tester.pumpWidget(widget);
  expect(buildCounter, 1);
});
```

**Comment by FilledStacks** [comment]
Awesome @seanmoore1976 Thanks for the update.

**Comment by FilledStacks** [comment]
If the test above reproduces the issue we should get this fixed and pushed as soon as possible. @seanmoore1976 we're expanding the teams responsibilities to tackling open source issues as well. We might take this off your hands if one of the devs get a chance to start working on this soon.

**Comment by aicodechef** [comment]
Ok, that sounds great! Apologies for the delayed response.

**Comment by bats64mgutsi** [comment]
@FilledStacks this [pull request](https://github.com/FilledStacks/stacked/pull/235) fixes this issue.

**Comment by FilledStacks** [comment]
Pushed in v1.9.4 . If it still happens we'll look at it further.

**Comment by steebchen** [comment]
I am running into this. I don't have a repro at hand but it's definitely not disposing anything when using `nonReactive`, while it is disposing correctly when using `reactive`. It calls the `onDispose` callback of the `ViewModelBuilder` widget, but it does not call the `onCancel` method in the extended `StreamViewModel` class. I'm new to flutter so if this is a different issue, please let me know if I should create a new issue for this.

**Comment by aicodechef** [comment]
Permanent unsubscribe.
