### ISSUE TITLE
StackedApp Route Path Builder

### ISSUE THREAD

**Issue by manafire** [Stacked-Org/stacked#226]
The latest update featuring code generation is absolutely amazing and super simplifies some of the things I stumbled over when initially switching over to Stacked last year.   Refactoring with the new `@StackedApp` annotations has been a piece of cake - easy and painless - with one snag I encountered: there's no provision for route name generation based upon arguments, which is important for analytics integration.  

I'm new to mobile analytics (coming from web), but _assuming_ it should work pretty much the same, you'd want the "url" to include instance-specific identifying information so you can answer questions like "How many people viewed product X?" (which you may track in analytics instead of the DB).

I'm proposing a new feature that would, perhaps, work something like this:

```
@StackedApp(
  routes: [
    MaterialRouteBuilder(classType: ProductView, pathBuilder: (arguments) => '/products/${arguments.id}');   
    ...
])
```

which would even allow you to do something like:
```
MaterialRouteBuilder(classType: ProductView, pathBuilder: (arguments) => '/products/${toKababCase(arguments.name)}');
```

Thanks again for all that you've done and continued to do for the Flutter community.  The tutorials and Stacked framework have been a total game-changer and demystified Flutter for me!

**Comment by FilledStacks** [comment]
@manafire sorry for the late reply. I missed this notification. This is a good suggestion. 

Traditionally I've been tracking my analytics through the route observer which removes it from the router code itself. Where would you be using the path builder output value?

**Comment by manafire** [comment]
@FilledStacks Not a problem.  I know you're a busy man.  (I did beat your deadline on the abstract route feature as well - just in case you didn't see that one come through.)

Hmmm...  Maybe `pathBuilder` is the wrong approach.  Let me back up a bit.  To support dynamic paths, I modified Tutorial 39 [router.dart source](https://github.com/FilledStacks/flutter-tutorials/blob/master/039-firebase-custom-start-user-profile/lib/ui/router.dart) as follows:


```

class Routes {
  // fixed routes
  static const String home = '/';
  static const String productView = '/products';

  // dynamic routes
  static String product(String id) => '/products/$id';
}


Route<dynamic> generateRoute(RouteSettings settings) {
  switch (settings.name) {
    // ...
    case Routes.productView:
      var product = settings.arguments as Product;
      return _getPageRoute(
        routeName: Routes.product(product.id), // or by product.name ?
        viewToShow: ProductView(product: product),
      );
  }
}


PageRoute _getPageRoute({String routeName, Widget viewToShow}) {
  return MaterialPageRoute(
      settings: RouteSettings(
        name: routeName,
      ),
      builder: (_) => viewToShow);
}  

// elsewhere in App; to view specific product:
_navService.navigateTo(Routes.products, arguments: product);
```

As you can see any routes going to `Routes.productView` are intercepted and the route name is dynamically generated based upon the product id (or, perhaps possibly, name).  This is consistent with what you would see in Google Analytics for web-based use.  Again, I'm still trying to comprehend mobile analytics in Firebase so perhaps it's different (certainly do not understand why all of my `screen_class`es is `Flutter` or `MainActivity`, but that's another issue).

In any case, I think this illustrates the problem I was trying to solve when converting to the (absolutely brilliant!) new `@StackedApp` route annotation format which generates the following (minus my comments):

```

// app.router.dart - generated file
Map<Type, StackedRouteFactory> get pagesMap => _pagesMap;
final _pagesMap = <Type, StackedRouteFactory>{
  ProductView: (data) {
    var args = data.getArgs<ProductViewArguments>(nullOk: false);
    //
    // TODO: how set route name such that:
    //     data.name = "/products/123"  ???
    // 
    return MaterialPageRoute<dynamic>(
      builder: (context) => ProductView(
        key: args.key,
        product: args.product,
      ),
      settings: data,
    );
  },
}
```

I'm certainly open to other ideas you may have!  Feel free to point me in the right direction and I can see what I'm able to do to help.

**Comment by FilledStacks** [comment]
Thanks for the detailed issue response. I really appreciate it. 

What comes to mind immediately is to add some additional functionality to the route definitions. The first being a boolean to indicate if you want parameters in your navigation route. Maybe a bool called `emulateWebPaths`. If this is set to true then we can generate some additional functionality into router. 

1. We can add a `String toUrlParameters` function onto the `ProductViewArguments` (as an example). Which will return one of two standard url parameter concatenations 
   1. ?id=2&category=ship 
   2. /2/ship
2. This can then automatically be added to the name of the `RouteSettings` data object shown above. 

The onGenerateRoute matches the first part of the route (I think) that will have to be tested first. Then when you want to add your analytics you can simply add a route observer that tracks the entire nav path. This would then output `/products?id=2&category=ship` if format 1 is chosen. This could get ugly if you pass a lot of parameters to the view. 

I've personally never done it this way but I do like the idea of automatic event tracking, the furthest I've gone is adding the route observer to track all screens viewed. Since I pass rich data I simply track that in the ViewModel of the view on initialise. i log the events and the custom class type as properties so that we can use each property as a potential axis. But with this you can write 1 route observer that does the same for every path that comes in. Take the name, turn it into a Uri. Add each uri query param as a property, set its value and publish the event. I really like it. Could definitely start using it myself. 

Let me know if the above would solve it then I'll see when I can slot it in for development. Or if you could help with the implementation that would be amazing as well.

**Comment by FilledStacks** [comment]
@manafire That makes sense. I'll set a p3 label on this. the package sync for now is the most important on our side as well. So we'll focus on the null safety updates happening through the package dependencies being left out. Then I'll get back to additional features like this.

**Comment by yakupbaser** [comment]
hi, is there any update?

**Comment by FilledStacks** [comment]
@yakupbaser no update.

**Comment by surveshoeb** [comment]
@FilledStacks have set any timeline for this?

**Comment by FilledStacks** [comment]
@surveshoeb no. This doesn't seem to be a priority for almost all stacked developers. But this is something I'll consider as I'm thinking about the routing functionality in stacked.
