### ISSUE TITLE
Keeping Tabbed Widget in Widget Tree

### ISSUE THREAD

**Issue by davidferraro** [Stacked-Org/stacked#229]
Hey there, been loving the stacked architecture, it's greatly helped speed up my development as it's very intuitive to how I work.

I do have one question, when using the DefaultTabController - widgets are removed from memory in the widget tree unless they implement AutomaticKeepAliveClientMixin (see https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html). In various points, I'd prefer to not have the tabs reload if the the user is flipping back and forth to different tabs as it's making new network calls and re-running futures. However, as I understand the stacked architecture so far, stateful widgets themselves abstracted away. Anyway to accomplish this same effect using the stacked pattern?

**Comment by FilledStacks** [comment]
@davidferraro that's great to hear man. I'm happy that it's an easy to use setup, I wanted to share it because of that exact experience. 

That is a common misconception that I've seen with stacked. Stateful widgets are welcome, it's no different than a stateless widget. Stateless just looks cleaner which is why I opt for it in combination with flutter_hooks to do some of the potential state storage like controllers etc. But that doesn't mean I don't use stateful widgets. We use it a lot, for animation management, controller management, etc. 

It's perfectly fine to use the KeepAliveClientMixin.

**Comment by davidferraro** [comment]
Thanks for the reply, it was super helpful!
