### ISSUE TITLE
[stacked_firebase_auth] FirebaseAuthenticationResult has only uid and userToken information

### ISSUE THREAD

**Issue by merfire** [Stacked-Org/stacked#267]
All sign-in methods (email, google, apple, facebook) return `FirebaseAuthenticationResult` object that has only uid, userToken and errorMessage.
Is there a reason why only uid and userToken are returned and not the whole User object from FirebaseAuth that has uid, userToken, email, displayName, phoneNumber, photoUrl, and most importantly customClaims?
Is it better to return User object in FirebaseAuthenticationResult ?
And is it better to expose _firebaseAuth, that way all functions of FirebaseAuth.instance can be accessed directly?

**Comment by mrseth01** [comment]
I usually listen for `authService.authChanges.listen((user) {}` to get the user object and sync custom user profiles stored in Firestore.

**Comment by FilledStacks** [comment]
@merfire No reason the user object is not on there. I usually return only what's needed at the time and add as those requirements change. This way I know exactly what's needed. I don't want code exposed that won't be used. 

It could be better to return the user object and have properties on there for quick access. 

We could expose firebase auth as well. If you'd like you can make a PR I can review, otherwise I'll most likely only get to this in a week or two from now.

**Comment by merfire** [comment]
I can do this after finishing Facebook changes for stacked_firebase_auth.

**Comment by FilledStacks** [comment]
@merfire that would be great thanks.

**Comment by FilledStacks** [comment]
we now return the user in the Firebase Auth Result
