### ISSUE TITLE
Passing Down Page Controllers

### ISSUE THREAD

**Issue by yekta** [Stacked-Org/stacked#308]
I have a page which contains my own `TabBarView` and Flutter's `PageView` widget. Let's call the page `Home`.

`HomePageView` uses the page controller from its model, `HomePageViewModel`. `HomePageView` also passes that PageController down to the `TabBarView`. `TabBarView` passes the controller to `TabBarViewModel`, then uses `model.pageController` which is the PageController it passed down to its model to begin with.

My problem is, even though they share the same PageController, `TabBarView` doesn't display the `model.pageController.page` value in real time, it rather just grabs 1 value every time there I swipe between the pages.

So, I basically need to connect a tab bar widget and a pageView widget that are contained inside the same page. I need the parent and the two children to share the same PageController and have access to the page value in real time (and update in real time).

I was wondering what is the recommended method for achieving such a structure with Stacked?

**Comment by FilledStacks** [comment]
@yekta I don't have a recommended way to do that. I can say though that there should be no UI code in the ViewModels. That's for the view files. 

There should be no controllers or build context or anything from the UI side in the ViewModels code. So that's something that you would have to change if you want to follow the recommended way of stacked. Keep the responsibilities singular. 

How I would solve this is by adding a listener to both controllers. When it fires I'll update the other controller (the not firing one) and set the index to the same index of the one that just fired. The don't need the same controllers, they just need to be in sync.

**Comment by yekta** [comment]
Didn't know controllers count as UI code and not state related code that should live in view models. The main thing was that I also need the page index state as a continuous stream (Page 1, Page 1.642, Page 1.731, Page 2 etc.) in both widget's view model too, in order to trigger other things based on it.

Are there any examples of the use of page controllers for Stacked you can point me to so that I can see how it works in detail (what goes where)? Went through the examples in the repo before opening the issue but couldn't find one. 

Thanks for the fast response and the help.

**Comment by FilledStacks** [comment]
@yekta I don't have any examples, I'd usually say to handle it the flutter way meaning in the view file and abstract in there, but the viewmodels should be unit testable and not require things from the flutter engine to run.

**Comment by FilledStacks** [comment]
I don't have clear examples, but we keep controllers out of the Viewmodels. Viewmodels maintain app logic state, not the specific view states like controllers and things like that. It's probably not clearing up anything but I'm hoping through more examples we can make it clearer.

**Comment by JayPerfetto** [comment]
To add to this - while it may not be best practice, I do my best to keep UI controllers that need to be accessed externally (i.e) in a viewmodel in a ReactiveService class and just expose it via a local wrapper in the view models where it is used. This might not be Stacked best practice but it works for my use case where my app has a lot of remotely fired events that make the UI "do something"

**Comment by FilledStacks** [comment]
@JayPerfetto that makes sense. I always mention to devs to do what works for them and allows them long term maintenance if the pattern is adhered to for all future development in the code base. I provide "strict" rules mostly because there are some devs that don't do the best things for their code base when they have freedom haha. 

But I've also used similar things that you've done. It's basically exactly what I did with the form generation in stacked. It's all put into a mixin that bridges the gap between view and viewmodel without either one of them housing the controller itself.
