### ISSUE TITLE
Can we add a getter to access current user data inside stacked_firebase_auth service?

### ISSUE THREAD

**Issue by okabhay** [Stacked-Org/stacked#309]
I could not find any property or getter through which i can access current user data, can we implement one getter for stacked_firebase_auth service to get current user data.

**Comment by FilledStacks** [comment]
Sure. We can add that in

**Comment by amoslai5128** [comment]
How can I handle stacked_firebase_auth with JWT token when calling the firebase cloud functions?  
Like checking / counting down and renewing token by the expired date before it calls the RESTful APIs

**Comment by okabhay** [comment]
Hello @amoslai5128 you can

Get a [IdTokenResult] containing the users JSON Web Token (JWT) and
other metadata like  expirationTime, issuedAtTime along with signInProvider. 
By using

`authService.firebaseAuth.currentUser.getIdTokenResult();`
```
print(result.expirationTime);
print(result);
```

or  just for token

`authService.firebaseAuth.currentUser.getIdToken()`

If [forceRefresh] is `true`, the token returned will be refreshed regardless
of token expiration.

`authService.firebaseAuth.currentUser.getIdTokenResult(true);`

Thanks to @merfire

**Comment by merfire** [comment]
@abhay-osizone 
FirebaseAuth.instance is exposed through firebaseAuth variable in FirebaseAuthenticationService.
For example you can access current user like this:
`authService.firebaseAuth.currentUser;`

@amoslai5128 
I am not sure about cloud functions since I don't use them, but for regular REST API, you can send JWT token in http header.

You can get the token using: 
`FirebaseAuth.instance.currentUser.getIdToken()` 
or 
`authService.firebaseAuth.currentUser.getIdToken()`

`getIdToken` handles token refreshes automatically, in the documentation it says:

> Returns the current token if it has not expired. Otherwise, this will
> refresh the token and return a new one.

@FilledStacks 
If it is easier for users, Firebase Core and Auth can be exported for easier access and autocomplete without manual imports:
`export 'package:firebase_core/firebase_core.dart';`
`export 'package:firebase_auth/firebase_auth.dart';`
Idk what do you think about this?

**Comment by okabhay** [comment]
@merfire thanks,  i didn't notice.

**Comment by FilledStacks** [comment]
@merfire I think that's perfectly fine. I'm making releases for 2 packages now. I only have 20 minutes left of open source work but I can get someone to add that for us.

**Comment by amoslai5128** [comment]
> @amoslai5128
> I am not sure about cloud functions since I don't use them, but for regular REST API, you can send JWT token in http header.
> 
> You can get the token using:
> `FirebaseAuth.instance.currentUser.getIdToken()`
> or
> `authService.firebaseAuth.currentUser.getIdToken()`
> 
> `getIdToken` handles token refreshes automatically, in the documentation it says:
> 
> > Returns the current token if it has not expired. Otherwise, this will
> > refresh the token and return a new one.
> 
> @FilledStacks
> If it is easier for users, Firebase Core and Auth can be exported for easier access and autocomplete without manual imports:
> `export 'package:firebase_core/firebase_core.dart';`
> `export 'package:firebase_auth/firebase_auth.dart';`
> Idk what do you think about this?

Thank you all for the quick and detailed response. I knew firebase auth has API for getting idToken, but what's the best practice for the following case?

Let's say I have multiple ViewModels that have actions rely on a user token to fetch the APIs, it shall refresh per 55 mins and I want it works in the background rather than checking it every time before fetching API.
Should I make a centralized token state to expose the token and count it down to refresh?
Or should I just keep storing it into a local database?

**Comment by merfire** [comment]
@amoslai5128 
If you are using Firebase Auth you don't really need to worry about storing and refreshing the token, because Firebase Auth does all that for you. For HTTP I like using Dio library with auth interceptor that adds JWT token to header for every request.

If the user is signed in, this:
`await FirebaseAuth.instance.currentUser?.getIdToken()` 
will always return a valid token, because even if the token expires this function will check for that and return a new valid token automatically.
I suggest to just call this function and get JWT token before every HTTP request where token is needed. 
Like I said I haven't used cloud functions so you need to check how cloud functions work with firebase auth, specifically how to send JWT token to your cloud functions, here is a [hint](https://stackoverflow.com/questions/42751074/how-to-protect-firebase-cloud-function-http-endpoint-to-allow-only-firebase-auth) that might help you.

Note: @abhay-osizone mentioned `getIdToken(true)` which will force refresh the JWT token every time you call this function. I would suggest not to use this if you don't know what it is used for and to just use regular `getIdToken()` that will refresh the token only if it is expired.
