### ISSUE TITLE
Using FutureViewModel and IndexTrackingViewModel

### ISSUE THREAD

**Issue by ghost** [Stacked-Org/stacked#321]
Looking to use both of these, however it seems like I can only implement (or extend it) to one of them.

Anyone have any idea how to use both?

**Comment by JayPerfetto** [comment]
I had a similar problem because I wanted to use a Multi streams view model as my home container's view model with a bottom nav bar - i imagine you're in a similar situation - basically if you check out the code for IndexTrackingViewModel, you'll see that it really only has a few locally scoped variables that make it special - I copied that code into my home viewmodel which I had extend MultipleStreamsViewModel, and just re-implemented the index tracking logic in that. All the code in the view at that point is the same as a normal IndexTracking VM

**Comment by ghost** [comment]
@JayPerfetto Thanks, I have it working now with my own locally scoped variable, but figured it would be nice to use both. Apparently it's not possible? Bummer.

**Comment by FilledStacks** [comment]
@JayPerfetto yes, you're correct. It's a super basic class, it'll be better to host that in your own viewmodel if you're not going to need multiple viewmodels to take advantage of that. even then you can put it into a base viewmodel of your own and extend a future viewmodel from it.

**Comment by Ruslanbek0809** [comment]
I totally agree with @JayPerfetto way of implementing multiple viewmodels in one viewmodel
