### ISSUE TITLE
How to call parent viewmodel `initialise` from child viewmodel?

### ISSUE THREAD

**Issue by joshiprashanthd** [Stacked-Org/stacked#352]
I am creating a note taking app. This app has two views, one is to show grid view of all notes and second is to view and edit each note. Both views are bind with `AllNotesViewModel` and  `NoteViewModel` respectively.

So when I tap a note in `AllNotesView`, it navigates to `NoteView` with tapped note information like `title` and `body`. When I done editing in `NoteView` and update the `title` and `body` I expect to see updated values in `AllNotesView` also. But when I go back to `AllNotesView`, the state is not updated. For this I want to call `initialise` method of `AllNotesViewModel` to update the state of `AllNotesView`. 

But I can't seem to find way to do this. I can pass the `AllNotesViewModel` instance to `NoteView` and call `initialise` method on it, but I think there might be a better way to do this. Is there any way I can access the parent view model for situation like this?

**Comment by hurbes** [comment]
You can always call your `AllNotesViewModel's initialise` function whenever you return to this view

```dart
Future<void> navigateToNotesView() async {
    await _navigationService.navigateTo(Routes.noteView);
    initialise();
 }
```

Return a boolean value with  ` _navigationService.back(result: true )` which will indicate that if `AllNotesViewModel's initialise` needs to be called based on the actions performed in  `NoteView`.

```dart
// NoteViewModel
  _navigationService.back(result: isNoteEdited);
  
// AllNotesViewModel 
 Future<void> navigateToNotesView() async {
  final _navResult = await _navigationService.navigateTo(Routes.noteView) ;
    if (_navResult != null && _navResult) {
      initialise();
  }
}
```

**Comment by FilledStacks** [comment]
@hurbes is correct. @joshiprashanthd will close this issue now. We can re-open if you have more questions.

**Comment by d3tr0id** [comment]
@joshiprashanthd Hi, I know this issue is closed, but I still wanted to comment another possible solution for this. You could make use of the Reactivity by using a NoteService Class extending ReactiveServiceMixin that notifies your View models (extending ReactiveViewModel) about changes in your NoteService. In the NoteService you could place your logic for fetching and saving notes from the LocalStorage or your API. This means whenever a note in the NoteService Class is modified, your Views get rebuild automatically.
 Refer to https://pub.dev/packages/stacked at the ReactiveServiceMixin part. I hope this could help 😃
