### ISSUE TITLE
Enable facebook auth

### ISSUE THREAD

**Issue by papadiscount** [Stacked-Org/stacked#402]
Hello. In the changelog it is stated that

> Facebook (Removed flutter_facebook_auth dependency and its implementation since it was causing a MissingPluginException if the app isn't setup for Facebook Auth)

Is there a way to re enable it?

**Comment by FilledStacks** [comment]
@papadiscount no there is not. We found that if you don't initialise the facebook plugin it breaks all the other plugins because it crashes the method channel bridge. So we had to remove it. 

You'll have to implement it on your side. The code is quite simple, it's in the commit history just find the file and copy the function out as is.
