### ISSUE TITLE
formValueMap is empty if your initial page is a form

### ISSUE THREAD

**Issue by dheerajsarwaiya** [Stacked-Org/stacked#462]
Hi,

I followed your tutorial on boxtout. After implementing loginview and createview, I put initial route to LoginView. Then I ran the build_runner command.

I found out that LoginView form was not setting the formValueMap and instead throwing an exception "Unhandled Exception: Null check operator used on a null value"

However, when I clicked on Create Account, it worked perfectly fine. 

Then I reset the initial route to "startup page" and created a button to go to LoginView. Reran the build_runner command. In this case, Login form worked as expected. 

Is it an expected behavior or is it an issue?

**Comment by ameeruljunaidi** [comment]
I had the same issue.

Creating an account worked like a charm, but logging in was giving me null.

Tried your workaround (changing the initial route) and it worked.

**Comment by Zeedinstein** [comment]
I'm having the same issue, except changing the initial route to startup page and rerunning the build_runner command has not fixed the issue. I have stacked version 2.2.2 and stacked_services 0.8.10 installed. My sign up page works fine but the login page just keep saying null for the form values.

**Comment by FilledStacks** [comment]
I haven't seen this error but I've seen it reported in the comments as well. I haven't seen this before. Might be due to a recent flutter update. I'll have to check if it's happening for me as well and then see what to do to fix it.

**Comment by Afsal102** [comment]
@FilledStacks  i found a fix for this , rather than using a library builder i tired using a PartBuilder with the annotation and it worked fine.

**Comment by kenyons** [comment]
For me, the initial screen does not make any difference.  It works fine in the iOS simulator, but not on an iOS device.  In debugging, it seems that the listeners on the TextEditingControllers are not being called therefore _updateFormData is not called when the fields are edited.  I added a stopgap fix by just updating the formValueMap myself in the onMainButtonTapped function.  

@Afsal102 could you elaborate on your fix a bit?

**Comment by FilledStacks** [comment]
@kenyons is this still happening?

**Comment by kenyons** [comment]
In preliminary debugging, it seems to be fixed.  When saveData() is called,
the map is now populated with the field data without me having to do it
manually.

**Comment by Turbo0x03** [comment]
Has anyone found a fix for this? Still getting this problem!

**Comment by FilledStacks** [comment]
@Turbo0x03 can you share an example where this happens please along with the steps to reproduce in that example.

**Comment by Turbo0x03** [comment]
@FilledStacks the problem is in the 'Box't Out' app, when you get redirected from the 'Startup Page' to the 'LoginView'.  If you press the Login Button without inputting anything, nothing happens, sometimes even if you input the username and password afterward, still doesn't get triggered. 
![d4e72db7a87407d1b7a3de3264ede25d](https://user-images.githubusercontent.com/57810455/150183611-0c7c6629-fa6a-4630-8b9b-5bb595f2dcc9.png)


My workaround was:

Overriding the setFormStatus inside LoginViewModel
```
  @override
  void setFormStatus() {
    Map<String, dynamic> newData = {
      'email': emailValue ?? "",
      'password': passwordValue ?? "",
    };
    formValueMap = newData;
    notifyListeners();
  }
```
and call it again inside saveData() into AuthenticationViewModel

```
  Future saveData() async {
    setFormStatus();
    updateButtonState(ButtonState.loading);
    setValidationMessage(null);
    notifyListeners();
    await Future.delayed(Duration(seconds: 2));
    log.i('valued:$formValueMap');
}
```

**Comment by eb-so** [comment]
@Turbo0x03 @kenyons I tried all of your suggestions but none of them seems to be a bug in the form generator but rather a bug in the boxtout project which is currently in halt status 


@Turbo0x03 
> @override
>   void setFormStatus() {
>     Map<String, dynamic> newData = {
>       'email': emailValue ?? "",
>       'password': passwordValue ?? "",
>     };

Instead of doing that you can just do it in [here](https://github.com/FilledStacks/boxtout/blob/afaa7a399caef88a548287e61e8c3a80efb8570b/src/clients/customer/lib/ui/login/login_viewmodel.dart#L18)
