### ISSUE TITLE
Reactivity improvement inquiry

### ISSUE THREAD

**Issue by Silfalion** [Stacked-Org/stacked#545]
Hello FilledStacks!

I was wondering what you meant by reactivity not being the most efficiently handled in Stacked, please. Could you elaborate a little more on what is inefficient about it?

**Comment by FilledStacks** [comment]
@Silfalion that was a comment I made when I had the miss perception that rebuilding the entire screen would be expensive. When in actual fact it's not. Flutter is built the automatically optimise your widget tree. So rebuilding the entire view has actually been perfect so far with no performance issues.

**Comment by Silfalion** [comment]
Ah I see. that's awesome. Thank you @FilledStacks 

Frankly, I'm getting too lazy to try other state management solutions because of how good stacked is. Just didn't fiddle around with the possibility of having multiple states instead of just busy or not busy yet. Do you think this would be implementable in Stacked by passing say an enum for example as a generic type?

Sorry if this is out of the scope issue, I can open another issue if that's preferable.

**Comment by FilledStacks** [comment]
@Silfalion hi. we don't really need multiple states. Any variable in the viewmodel can be considered state. Busy is the most common across all apps which is why it's in there. Any other state can be tracked with a variable in the viewmodel. 

Happy I could answer your question. I'm doing some big updates to stacked this year so it'll get even better!
