### ISSUE TITLE
Flutter Web redirect support

### ISSUE THREAD

**Issue by mraaz97** [Stacked-Org/stacked#803]
Currently Navigation works fine also on web, however there is no support to protect named routes in Flutter Web. Go_router provides a redirection function on each new navigation event or at the route level for a specific route. We use Stacked in a corporate environment and would love to use it in our Web projects too. Currently as a workaround we are using go_router in our Web Projects.  Since Flutter 3 with better support for Web, Flutter Web gains more traction therefore it would be super nice if Stacked provides support for this and general Web support. I would offer myself to implement the feature when being guided from the stacked team. I need to understand how it works at the moment and would love to discuss how this can be implemented, maybe in a call to get deeper insights from stacked navigation.
Cheers!

**Comment by FilledStacks** [comment]
Hi @mraaz97 that's a generous offer. 

At the moment we're focused on building applications (mobile, desktop and web apps). We don't believe that Flutter web is viable for a website, regardless of how much we love the technology. That being said, I do think it might be worth implementing basic navigation functionality for web including route guards. 

Because applications rarely require route guarding since you can never manually go to a route, it has never been a high priority for us. 

Do you mind telling me where you work / which corporate environment you work in. I'm trying to see where Stacked is used and what type of teams / devs are using it. I'd like to communicate more directly with users like yourself.

**Comment by mraaz97** [comment]
Thank's for the swift reply @FilledStacks!

When talking about Flutter Web, I am referring to Web Apps and not Websites. And you can manually go to a route by typing the url manually in to the browser or why do you say it's not possible? However I understand if it's not in your scope! Thanks anyways.

**Comment by FilledStacks** [comment]
@mraaz97 You're not able to do that for iOS, Android, MacOS, Linux or Windows apps. 

And the good web apps built with Flutter also doesn't allow it. Like rive's web editor. So we've never had to guard against it because we only build mobile or desktop apps. 

But it's definitely a valid scenario for many types of web applications.

**Comment by FilledStacks** [comment]
This issue has been addressed with the new addition of the RouterService and using the latest AutoRouter generator with some additional changes. 

There's not much documentation but you can now supply [Redirects](https://github.com/FilledStacks/stacked/blob/8478346fbc77585b436b71f7005bfc9b74d17a7b/packages/stacked/example/router_example/lib/app/app.dart#L34) for top level and nested routes within the app.dart annotation. 

In addition to route guards. 

I'll be working on the documentation this week as well as the code for the new videos to share all this functionality.
