### ISSUE TITLE
Support for multiple futures in a view model, each triggered by a different event

### ISSUE THREAD

**Issue by smokelaboratory** [Stacked-Org/stacked#85]
Hello!
Wonderful package. Loved it!
I've a very general use-case and I'm having a hard time achieving it with this architecture.

Suppose, a screen has multiple APIs associated with it and each of them is triggered by a separate event. For instance, when a screen opens up, I need to fire one of the associated APIs; on click of a button, I need to hit another API; finally, when the screen closes, 3rd API should be called.

Is there a way to achieve this using `MultipleFutureViewModel` keeping `busy`,  `hasError`, `onError`, `onData` and all other perks of future view model intact for **each** API?

**Comment by FilledStacks** [comment]
@smokelaboratory No. The FutureViewModel is specifically for a ViewModel that requires data before it can function, that's why the data returned is stored locally in the object. So that we can access it in the view. 

It's not for running a general Future. That you can simply do by extending the BaseViewModel. The FutureViewModel and StreamViewModel is specifically for fetching data using a future and storing that data in the model.

**Comment by smokelaboratory** [comment]
Ok. Thank you for explanation. Closing the issue.
Also, as I strictly want to follow the guidelines of your architecture in my project, what is the best way to do it using  `BaseViewModel`, keeping all features of a `FutureViewModel` for each future task?

**Comment by FilledStacks** [comment]
i don't exactly know what you're asking. BaseViewModel is the basic viewmodel as I've been using through all the videos. It's just a change notifier where you can call notifyListeners in with some extra functionality that's not required. It's just there to make your life easier.
