### ISSUE TITLE
```criticize``` I found your this approach is not related to any kind of state management Core concept

### ISSUE THREAD

**Issue by Manishmg3994** [Stacked-Org/stacked#858]
Hi there , As I got to know your stacked  ```State Management ``` with MVVM  package , I explored it ,read your this package documentation but don't found it useful , as you called this a state management package but even though it re renders the whole build function on every view model UI rendering call , but as I know the definition of state management only re building of those UI components takes place which have a data change . I wish you will enhance your package build to that concern , Also I request you to provide me necessary  permission in regard of your MIT LICENCE ,so that I can also contribute and enhance for my own projects and change some core logic with a better approach
 ## Thanks in advanced

**Comment by FilledStacks** [comment]
Hi Hi,

I don't quite know what you're saying. State management is a term for when you want to manage the state of an object, in this case, the state of the view is managed in the Viewmodel and we display that state to the user through the View. 

This is the exact definition of a state management system. It does not dictate the pattern used to rebuild or manage the UI. For instance `setState` is a state management solution built into Flutter and rebuilds the entire view. 

There's also an idea around Flutter, especially with beginners, where they think the build method should "never" fire, which is not the case. In fact Flutter is built so that you can fire that build method 60 times in a second and still perform well, the widget and element tree optimisations take care of that. For instance, in a pure flutter app,  when you lock your phone and unlock the build method fires, when you show a snackbar, dialog or bottom sheet the build methods of everything on screen fires. If you open or close the keyboard every build method fires as well. The build method firing is not an issue.

The reason we never focused on rebuilding only a small portion of the screen is that we never had any performance degradation. With that said, there are [selectors](https://github.com/FilledStacks/stacked/blob/master/packages/stacked/README_old.md#selectorviewmodelwidget) you can use to rebuild only when a specific property has changed. 

In addition to that Stacked is built so it's 100% granular down to the letter in text. You can always create a widget with its own viewmodel and it will only update when you call `rebuildUi` in its viewmodel and won't rebuild it any of the viewmodels above it rebuilds. 

If you need more concrete answers then you can put code down and I can help you figure out how to implement what you want.

**Comment by manishgautammg3994** [comment]
ok fine keep it up...... , i will also explore it (more in depth)
