### ISSUE TITLE
Stacked with AutoRoute navigation

### ISSUE THREAD

**Issue by tomasweigenast** [Stacked-Org/stacked#863]
Hello. I'm using Stacked to manage the state and AutoRoute the routing. It's a Flutter Web plugin. I have a route that takes path parameters, like so:
`/activities/:id`
then I create the view like this:
```dart
class ActivityView extends StatelessWidget {
  final String id;

  const ActivityView({@PathParam("id") required this.id, super.key});

  @override
  Widget build(BuildContext context) {
    print("id: $id");
    return ViewModelBuilder<ActivityViewModel>.reactive(
      viewModelBuilder: () => ActivityViewModel(id),
      disposeViewModel: true,
      createNewViewModelOnInsert: true,
      builder: (context, model, child) {
             ...
```

The problem is that the ViewModelBuilder is not rebuilt when I manually change the id in the URL. What can I do it?

**Comment by FilledStacks** [comment]
Hi @tomasweigenast AutoRoute doesn't work as expected with Stacked. Since they moved the Navigator 2.0, which Stacked doesn't use. 

This is actually a research task that's coming up for me in the next week or two after I release the new Flutter web video I'm working on.

I know some people are using it with AutoRoute's new version but I have not used it myself so I wouldn't be able to guide you. I will have clarity on this very soon, but until then I won't be able to help you with it. 

I'll add a label to come back to this when I've done my research.

**Comment by tomasweigenast** [comment]
Nice @FilledStacks, thank you. I was thinking of moving out of AutoRoute because it does not work well in Flutter Web, specifically when not using the `/#/` url strategy, but Stacked navigation does not convince me at this moment,

**Comment by FilledStacks** [comment]
@tomasweigenast me neither. We have not fully explored Flutter web with Stacked. I'm doing that in the coming weeks and will see what we need to do to ensure we satisfy some of the different requirements we have on web compared to mobile.

**Comment by FilledStacks** [comment]
We've now added functionality and guides to handle nested url routing scenarios. Documentation will be updated in the coming weeks.

**Comment by Abhijit-Revamp** [comment]
@FilledStacks Is the documentation complete with nested url scenarios

**Comment by FilledStacks** [comment]
No, I never got around to updating the docs, but it's in a video.  You can find it [here](https://youtu.be/cGdNRnBdWpw?si=WKxlFIshnbg3MsMl)
