### ISSUE TITLE
[logger]: errors are not printed

### ISSUE THREAD

**Issue by buehler** [Stacked-Org/stacked#877]
Hey @FilledStacks

Thank you, big time, for this lib! It makes coding flutter apps a real breeze.

I currently struggle with the application logger though. Without any special configuration, the logger does a nice job, however, when `logger.e('An Error', <some Error object>, <some stacktrace>)` is used, the error is not printed out. This would be really helpful in local development to see the actual error (if set).

Wdyt?

Cheers

**Comment by FilledStacks** [comment]
@buehler thanks for using stacked! I appreciate it. 

This is most likely a bug 😅  I'm busy with the new Flutter Web series using the updated stacked, if I finish my dedicated tasks for that this week I'll tackle this bug in the week. Otherwise, probably next week. 

What would help is if you modify the logger to get it printing out the way you want, then post that file here. Then I can update the generator to spit out the updated version of the logger and push that.

**Comment by buehler** [comment]
Hey @FilledStacks 
Will do, as soon as my build works, I can try to make a PR ;-)

**Comment by buehler** [comment]
It should not be that big of a change.

**Comment by FilledStacks** [comment]
Much appreciated @buehler
