### ISSUE TITLE
Test different options to replace Observable_ish

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#88]
There are a few questions some devs have asked about the use of observable_ish that encourages us to look at using different reactive packages or functionality provided by flutter. 

- ValueNotifier: Comes with Flutter. No packages required, hoping that it doesn't affect unit tests in services.

- Get Rx: The most common one but we will not include an entire framework package (Even though it's pretty small) just to use the .obs functionality. We will reach out to the developer of get and hear if we can break that into a separate package or if we can duplicate that functionality in our project with their permission.

**Comment by jonataslaw** [comment]
Flutter's ValueNotifier is always a good option, but it doesn't support Streams (it's just an ObservableList of VoidCallbacks, which loops and calls all functions in that list when notifyListeners is called, and in its set method there's a notifyListeners, which does any changes to the variable triggering the event. It's a very simple, but useful approach). ValueNotifier also has no callbacks for you to know what has changed, and if a Stream is used only to deliver this, you will have the Stream + ObservableList overhead used in ValueNotifier, while you would only use 1 single Stream with Rx. I also considered using ValueNotifier to build Get's state manager, it's good for mass updates (because it's literally a loop of VoidCallbacks), but it doesn't do very well in performance when you need to deliver a single update, since the whole list is covered, that was one of the reasons that made me support Streams, and build the Rx under them. If you do not need to merge streams, you do not need to output a stream, and you do not need to know what value has been changed, and you still make updates in blocks, ValueNotifier should suit you. As you need to use anything else, using ValueNotifier will end up becoming less performative, and more laborious.
I just checked observable_ish and despite using 2 streams and a proxy, they seem to have been inspired by the same legacy lib from dart 1 that I looked at when I decided to do Rx. Despite a different approach, the output of Get is very similar to that of observable_ish, and the final code is very similar, which would cause minimal modifications.
Well, those were my considerations when I created Rx, I am making it clear here just so that you have better targeting than you should use. For block update situations, ValueNotifier is enough for you, if you’re looking for it, maybe it has what it takes, but if you need to know what’s changed, or if a user might be interested in using Streams, I’d say you should explore another solution that is not ValueNotifier, and always remember it is O(N) for adding and removing listeners and O(N²) for dispatching notifications.
About the package, in the last update I divided the package into blocks.
When importing Rx features, the other package dependencies will not be compiled.
You can see this repository https://github.com/jonataslaw/getx/tree/master/benchmark , and compile, and you will see that the size of the application using Rx + Obx is smaller than all other packages, even using the full Get package as a dependency.
The Rx folder has all the elements of Rx, and if you only use it, only it will be imported into your project, but nothing prevents me from putting it in a separate repository in the future, including opening an issue on Get to ask people if they would prefer several micropackages, or a single package separated by folders, I will decide this before launching 3.0 (there will be almost no break).
If you need help too, I don't have a lot of free time, but I can help you.

**Comment by FilledStacks** [comment]
@jonataslaw Thanks for the detailed description. I appreciate all the details and it'll definitely help in my decision. We definitely don't need to merge streams. The only thing I want is to change an existing service into a reactive service in the least amount of code changes. Currently we wrap the type in RxValue then use .value where it's accessed. I'd like the "improved" approach to also only have those 2 steps. 

And about knowing what changed, I will need that in the future given one of the updates I want to make is partial rebuilds given the property the widget is listening too has changed. 

Thanks again for all your input. I also only get 1 days every 2 weeks to work on our open source packages so I'll go through things in my own time and create what's needed. Thanks for the offer and keep up the good work, can't wait to see what's in v3. I've only used the navigation so far, but I keep an eye on everything else being done in your package.

**Comment by binaris-no** [comment]
Replacing observable_ish would be big plus for Stacked. From what I've seen observable_ish doesn't seem too maintained, it has no tests and there aren't many good examples in its own context or together with Stacked. And it is quite a crucial piece.

**Comment by FilledStacks** [comment]
@binaris-no agreed. The max extent I was using it for is covered although it doesn't have reactive map support. I will look into this as soon as I get some free time on my hands.

**Comment by YTarikKalyoncu** [comment]
Any update? @FilledStacks 
Get Rx implement could be great. observable_ish is not track elements, inside of a class.

**Comment by FilledStacks** [comment]
@YTarikKalyoncu I'm reluctant to include the entire get package in my package. There's no update on the functionality yet but I have almost completely stopped using observable_ish now. I've implemented a notifylisteners in the service which can now be used after updating a value to notify all the viewmodels listening.

**Comment by nicoache1** [comment]
@FilledStacks do you have some examples of how we should use this without `observable_ish`? I mean `addListenter/removeListener + notifyListeners()`

**Comment by FilledStacks** [comment]
@nicoache1 you don't have to add any listeners. The viewmodel that subscribes to the service does that. You simply just call notifyListeners in the service.

```
class MyService with ReactiveServiceMixin {

  String _value = 'default';
  String get   value => _value;

  void updateString() {
   _value = 'updated';
   notifyListeners();
  }
}
```

That's it. The viewmodel will then add the service as a reactive service in its list.

**Comment by FilledStacks** [comment]
I've decided that we'll remove reactive values and recommend the notifyListeners call in the service instead. This solution has been great and provides more fine grained control to when you want your service to rebuild the viewmodels.
