### ISSUE TITLE
[StackedServices] Nested Navigation BUG

### ISSUE THREAD

**Issue by devRaphe** [Stacked-Org/stacked#880]
Hello Team. @ferrarafer @FilledStacks 

 - FIRST ISSUE IS THAT I CAN'T NAVIGATE TO A NESTED VIEW WITH A NAMED ROUTE, ONLY WIDGET ROUTING WORKS.

 - SECOND ISSUE IS THAT WHEN THE APP STARTS FROM THE [StartupView] AND NAVIGATES TO THE [NESTED ROUTE VIEW], AN ERROR IS THROWN WHICH IS "Multiple widgets used the same GlobalKey."
 BUT WHEN THE APP STARTS DIRECTLY TO THE NESTED ROUTE VIEW THEN THE ERROR IS NOT THROWN.

 I BELIEVE THIS SECOND ERROR HAS TO STILL DO WITH THE WAY
 THE NESTED NAVIGATION IS SET UP.
 
 TO REPRODUCE THIS ISSUE, HERE IS A REPO LINK TO A MINIMAL APP.  [APP](https://github.com/devRaphe/nested_navigation_bug)

![Screenshot from 2023-03-02 11-08-24](https://user-images.githubusercontent.com/72768624/222907295-213db007-977e-404f-a14a-a231278cf00e.png)

**Comment by ferrarafer** [comment]
Hi @devRaphe, how is going?

First of all I have to say that I didn’t used the nested functionality before 😅  because I used the old way. With that said, I think you miss understood the functionality. The parent route of the nested routes does NOT exist, is a way to group your nested routes. That’s why in your application you don’t have a typed navigation function to PostsView or UsersView, you can’t go there, you can only go to their nested routes. On the parent view of your nested views you need to call the `ExtendedNavigator()` function.

Take a look at the documentation [here](https://pub.dev/packages/stacked/versions/2.1.1#nested-navigation).

If I’m wrong, @FilledStacks is going to correct me asap 😄

**Comment by devRaphe** [comment]
Hmm @ferrarafer  the issue is that I can't use route names to navigate into a nested route but I can Navigate to the View by passing the widget. The issue is why that isn't happening, since the difference just between named routes and widget routing. Becuase Internally when I provide the Extended navigator id to the navigation service, GetX uses the Id provided to find the nested navigator key and it navigates inside its parent but when I do the same with a named route it says the route can't be found, even the generated code creates a separate for UserView names UserViewRoutes, so technically its suppose to work, but I think the issue is from how the routes are setup. Lets wait and see what @FilledStacks thinks when he properly looks at the minimal project, especially the router generated code.

**Comment by FilledStacks** [comment]
After looking at your implementation I can see the issue and Fernando is right, and wrong 😊 When you’re creating a nested route with UserView you’re telling Stacked that “The user view has its own set of routes with its own router inside it”. 

This means that the UserView has to use that Router in order for you to navigate to the routes within it. You can think of the View that has the nested routes as the “Housing View”. It’s only purpose is to setup the router for the nested views and show the initial view. This is an over simplification because it can have its own UI, but you have to use the router in it. 

So if you update your `UserView` to this

```dart
class UsersView extends StatelessWidget {
  const UsersView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    log('UsersView.build()');
    return ViewModelBuilder<UsersViewModel>.reactive(
      builder: (context, model, child) => ExtendedNavigator(
        router: UsersViewRouter(),
        navigatorKey: StackedService.nestedNavigationKey(userRouterId),
        initialRoute: UsersViewRoutes.usersLandingView,
      ),
      viewModelBuilder: UsersViewModel.new,
    );
  }
}
```

What that means is when you navigate to your `UsersView` you use the normal navigator since it’s at the root level of your navigator. To navigate within that navigator you then use the `nestedNavigationKey`.

To make the example work add a new view that's your default view.`stacked create view usersLandingView` and move your old UI in there. Then you can update your `app.dart` file to the following. 

```dart
MaterialRoute(
  page: UsersView,
  children: [
    MaterialRoute(page: UsersLandingView),
    MaterialRoute(page: UserDetailsView),
  ],
),
```

It works on my side using the normal named navigation.

**Comment by FilledStacks** [comment]
@ferrarafer this should move to the docs as well. We'll add some more docs as we get our content pipeline streamlined.

**Comment by devRaphe** [comment]
Great, I will try it out in my production project. @FilledStacks can you also verify that this current implementation fixes the issue with Flutter complaining about duplicate keys in the widget tree.

**Comment by FilledStacks** [comment]
Yes, that happens due to the miss use of the routers.
