### ISSUE TITLE
Add firebase services

### ISSUE THREAD

**Issue by chetanchoudhary08** [Stacked-Org/stacked#92]
Like there is navigation service, dialog service and snackbar service, 

1. It would be good to have firebase services which would help login by various methods (mobile number, social auth, email etc). This would speed up development.
2. Firebase notification service with common useful methods
3. Firebase storage service with common useful methods
4. Firebase firestore service with common useful methods
5. any other firebase service which would be helpful

**Comment by YazeedAlKhalaf** [comment]
This is a great idea! but I think sometimes you won't need them and they will make the app a lot heavier and larger. Not all apps need firebase. That's just an opnion.

**Comment by YazeedAlKhalaf** [comment]
https://github.com/YazeedAlKhalaf/Compound/tree/master/lib/src/app/services

Here I have some services you may like and see helpful.

@FilledStacks What do you think?

If it is good I could do it for the community!

Although I feel it is so app-specific.

**Comment by FilledStacks** [comment]
@c1c2ai I think it's a good idea. That was the next package that I was going to add into the stacked repo since we also use it often on our side. 

@YazeedAlKhalaf I'll compare the services to what we use in production and see what to do. I'll create the package at some point then you can move some of them over. I have the authentication service built already I just have to clean up the code a bit more and make it more configurable for other projects.

**Comment by YazeedAlKhalaf** [comment]
@FilledStacks That's great!

Just to be clear, You mean you will create a separate package for Firebase services, e.g `stacked_firebase_services`?

**Comment by chetanchoudhary08** [comment]
@YazeedAlKhalaf  Yes not every app would use firebase, but many many will use. Firebase has become the easiest and first choice of many developers to start with and test out their ideas. If you feel that this would make the app heavy then even having another package like stacked_firebase_services would be good to go. But I really feel the need for it as many developers start with firebase and stick to it for quite some time.  There are many methods which can be added to speed of development. I am trying to add a general purporse login by mobile currently, will share it soon after completion

**Comment by JayPerfetto** [comment]
This would be an incredible package to have - I love the Stacked architecture, and it has completely revolutionized my app building workflow. My velocity is so much better, as is my maintainability and consistency. I love how the hooks, services, and architecture packages are separated, and a stacked_firebase_services package would be a godsend on top of an already incredible "framework"

**Comment by YazeedAlKhalaf** [comment]
Okay So just some curiosity, Are you willing to work on it? no offense just a question

I am so I will start the package and add it as a pull request then we can all contribute to it, What do you think guys?

One **NOTE**:
**The functions should be customizable so that the developer can customize it and change things to fit his needs, for example, add an argument for when creating a user for additional functions like creating a user document, etc..**

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf i plan too. But I don't exactly know when i'll do that. i have written about 4 firebase services in 4 different projects so I know what is required for some of the production applications and I have the code for it already. mobile verification, basic sign up, login, reset password etc. I'll probably only be able to look at that maybe the week after next. next week i'm making the new video then the week after that I'll probably have some time on Sunday to start the package.

**Comment by chetanchoudhary08** [comment]
@YazeedAlKhalaf yes, I am in for it

**Comment by FilledStacks** [comment]
Closing as duplicate of [102](https://github.com/FilledStacks/stacked/issues/102) and tracking all progress in that issue
