### ISSUE TITLE
[bug]: Why Stacked uses GetX? (Just curious, no flame)

### ISSUE THREAD

**Issue by scognito** [Stacked-Org/stacked#923]
### Describe the bug

I know this is not a bug, but the [link](https://github.com/Stacked-Org/framework/discussions) to the QA/Doc doesn't work.
I'm working on a (not small) commercial app since october and discovered for the first time Stacked. I really, really appreciate it: very easy to use, no steep curve for learning, everything works perfect (still something to learn).
I'm asking this question because I noticed it uses the "not so loved by community" library get (Getx).
Is there a particular technical reason? I'm a bit worried about 2 things:
1) The library is like a framework inside a framework, hiding a lot of flutter concepts
2) It is 10 months old + there is only 1 mantainer (IIRC): what happens when major version of Flutter will be out that potentially can have breaking changes

Again, this is not a criticism, just a curiosity for a library that I really appreciate a lot.

PS: We are using 2.x version, I don't know how easy will be porting to 3.x :)

### To reproduce

None

**Comment by FilledStacks** [comment]
I appreciate the question, it's actually something that I want to remove at some point. When I started using Get (it wasn't even called GetX yet) for Stacked I just needed a way to navigate without providing the context. We have our own setup from before built with pure flutter (which you can see in [this old video](https://youtu.be/kopdISefbJc)). At the time get was doing only that, giving a nice way to access context based objects in Flutter without the requirement to have the context. 

As it's been growing I've been wanting to remove it completely. This is only used in the `StackedServices` so Stacked won't be that affected by the changes. We've been careful and intentional with our separation of concerns to ensure we can easily replace it. It will cause a lot of changes, some breaking, so I'm delaying it as far into the future as possible. One of the potential replacements is OneContext. With that we'll have to implement our own snackbar fuctionality, bottomSheet, dialog, and navigation interactions. 

It's a large undertaking and at the moment not a large payoff. Since we tree shaking in Flutter none of that other code makes it into the final build. So for now it's not harming us. 

In terms of them not updating to latest Flutter. I would simply fork and use that until I find the time to rebuild the stacked services to use a newer solution for "context-less" flutter framework interactions.

**Comment by scognito** [comment]
I really appreciate the answer. Seems legit, thank you!
