### ISSUE TITLE
[bug]: child widget on viewmodel ready is not getting called

### ISSUE THREAD

**Issue by rehan-505** [Stacked-Org/stacked#936]
### Describe the bug

onViewModelReady of child widget is not getting called when we do notifyListener in parent widget. Even though constructor of child widget gets called but onViewModelReady  of the child widget doesn't get called.

### To reproduce

1.) Make a parent widget extended with stacked view, having a view model  assumingly named ParentViewModel.
2.) Pass a child widget which is also extended with stacked view  as a child to parent. Child widget will have it's seperate viewModel i.e. ChildViewModel
3.) By default both parent and child are reactive true.
4.) On Some Random button click call notifyListener for parent in parent's viewmodel 
5.) Expected Behaviour: Child widget gets rebuilt along with its viewmodel and child widget's onViewModelReady method is called. 
6.) In reality : Child Widgets build method gets called but child widget's onViewModelReady method is not getting called.

### Expected behavior

When doing notifyListener in parent widget's viewmodel, Child widget should be rebuilt along with its viewModel and child widget's onViewModelReady method should be called.

**Comment by JaidynBluesky** [comment]
If the child widget is definitely getting rebuilt, have you tried setting `createNewViewModelOnInsert: true` in the `ViewModelBuilder.reactive()` constructor?

**Comment by rehan-505** [comment]
yeah I have tried that (and every other method available) as well

**Comment by rehan-505** [comment]
> If the child widget is definitely getting rebuilt, have you tried setting `createNewViewModelOnInsert: true` in the `ViewModelBuilder.reactive()` constructor?

yeah I have tried that (and every other method available) as well

**Comment by FilledStacks** [comment]
@rehan-505 That is not expected behaviour. it won't call onViewModelReady when the widget tree is rebuilt. If it does that it will require that onViewModelReady is called for every rebuild. Which happens when keyboard shows and closes, dialogs shows, notification tray is opened etc. 

The behaviour you're describing is not expected, how it's working now is. The same reason initState won't get called in a child stateful widget. Stacked follows the Flutter rebuild cycle exactly. We'll stick to that to make sure we don't introduce our own build cycles.
