### ISSUE TITLE
Stacked does not respect SafeArea

### ISSUE THREAD

**Issue by richard457** [Stacked-Org/stacked#940]
### Describe the bug

having this code at root `class SocialHomeView extends StackedView<HomeViewModel> {
  const SocialHomeView({super.key});

  @override
  Widget builder(
    BuildContext context,
    HomeViewModel viewModel,
    Widget? child,
  ) {
    return ScreenTypeLayout.builder(
      mobile: (_) => const HomeViewMobile(),
      tablet: (_) => const HomeViewTablet(),
      desktop: (_) => const HomeViewDesktop(),
    );
  }

  @override
  HomeViewModel viewModelBuilder(
    BuildContext context,
  ) =>
      HomeViewModel();
}` and try to add SafeArea as child does not work.

### To reproduce

class SocialHomeView extends StackedView<HomeViewModel> {
  const SocialHomeView({super.key});

  @override
  Widget builder(
    BuildContext context,
    HomeViewModel viewModel,
    Widget? child,
  ) {
    return ScreenTypeLayout.builder(
      mobile: (_) => const SafeArea(child:Text("A")),
      tablet: (_) => const const Text("A"),),
      desktop: (_) => const const Text("A"),,
    );
  }

  @override
  HomeViewModel viewModelBuilder(
    BuildContext context,
  ) =>
      HomeViewModel();
}

### Expected behavior

if on mobile safe area should work as expected

**Comment by CordMemescape** [comment]
@richard457 

Stacked doesn't do anything specific with the rendering of the UI. In fact, if you create a Stacked app using the web template, replace the `Padding()` widget on line 15 of `home_view.mobile.dart` with a `Container()` widget, and add a color to the container, you can see the SafeArea() being respected (running on a iPhone):

![safe_area](https://user-images.githubusercontent.com/100955529/237057477-e9d4a9a4-00c4-4499-9a28-e1337a962c36.png)

I've noticed that if I build for macOS or the web, I don't get a `SafeArea()`. This is a function of the `SafeArea()` widget itself rather than anything that Stacked is doing. So the question is, what platform are you building for? And, is this perhaps the behaviour that you're seeing?

**Comment by FilledStacks** [comment]
What @CordMemescape says is correct. We return the widget exactly as you build it. We don't interfere with Flutter rendering in any way.
