### ISSUE TITLE
Does ViewModelWidget have initState()?

### ISSUE THREAD

**Issue by azrael8576** [Stacked-Org/stacked#96]
I have a ViewModelWidget that wants to generate animation init value in initState(). And _animationController.forward();

Like this video: 
https://youtu.be/FCyoHclCqc8?t=1340

Does ViewModelWidget have initState()?
Or do I have other alternatives?

**Comment by ninest** [comment]
Does `onModelReady` do the job?

```dart
@override
Widget build(BuildContext context) {
  return ViewModelBuilder<ExampleViewModel>.reactive(
    viewModelBuilder: () => ExampleViewModel(),
    onModelReady: (model) {
      // initState code
    },
    builder: (context, model, child) => SomeWidget(),
  );
}

```

**Comment by JayPerfetto** [comment]
Hi - I arrived at this question because I am trying to pre-fill a text form field in a StackedHooks widget that uses useTextEditingController(). How would one do this, i.e on a profile-edit screen to prefill the fields with the user's information once they arrive from the stream? (the viewmodel for this is a StreamViewModel, so I want to call model.data in onModelReady - is this possible?

**Comment by FilledStacks** [comment]
@JayPerfetto [here](https://youtu.be/1PhAPWzGaM4?t=1327) you can see that i pass the data i want to prefil to the view I'm navigating too. In onmodel ready I check if it's not null, if it's not null i assign it to the textEditting controller. that's it. i don't pass them through a stream. The data is passed directly as an argument to the view so that it's there as soon as it's constructed.

**Comment by azrael8576** [comment]
@ninest 
Thank you. 
ViewModelBuilderWidget is work.
But I need state, as the AnimationController vsyn parameter.
ViewModelBuilderWidget, ViewModelWidget extends StatelessWidget.

**Comment by FilledStacks** [comment]
I would use the HookViewModelWidget and use flutter hooks for the animation controller. that takes the need for stateful widgets away. You can use the `useAnimationController` hook.

**Comment by danPyk** [comment]
@FilledStacks I would like to use HookViewModelWidget to create aminations, but when I'm trying to extend SingleTickerProviderStateMixin I'm reciving:
`SingleTickerProviderStateMixin<StatefulWidget>' can't be mixed onto 'HookViewModelWidget<HomeViewModel>' because 'HookViewModelWidget<HomeViewModel>' doesn't implement 'State<StatefulWidget>'`

I guess there's no way to handle it, because stacked have notihing to do with StatefulWidget?

**Comment by FilledStacks** [comment]
If you're using hooks for it then you don't need the mixin. That's the whole point of the Hooks package. To reduce the stateful code required for simple tasks. 

```dart
class VuiArtistCard extends HookWidget {
  const VuiArtistCard({
    Key? key,
    required this.artist,
    required this.busy,
    this.onImageCarouselChanged,
  }) : super(key: key);

  final Artist artist;
  final bool busy;
  final Function(MediaFile)? onImageCarouselChanged;

  @override
  Widget build(BuildContext context) {
    final animationController =
        useAnimationController(duration: const Duration(milliseconds: 500));

    final scaleAnimation =
        Tween<double>(begin: 0.9, end: 1).animate(CurvedAnimation(
      parent: animationController,
      curve: const Interval(0, 0.5, curve: Curves.easeOut),
    ));

    final translateAnimation =
        Tween<Offset>(begin: Offset(0, -10), end: Offset(0, 0)).animate(
      CurvedAnimation(
        parent: animationController,
        curve: const Interval(0, 0.5, curve: Curves.easeOut),
      ),
    );

    animationController.forward();

    return VenuSkeletonLoader(
      loading: busy,
      height: 300.0,
      widthFactor: 1.0,
      borderRadius: 12.0,
      includeText: true,
      child: AnimatedBuilder(
        animation: animationController,
        builder: (context, child) {
          final imageUrls = getImageMediaUrls(artist.mediaSafe);
          return Column(
            children: [
              Transform.scale(
                scale: scaleAnimation.value,
                child: Transform.translate(
                  offset: translateAnimation.value,
                  child: VuiCarouselImageCard(
                    height: 300,
                    mediaUrls: imageUrls,
                    onImageChanged: (imageIndex) {
                      onImageCarouselChanged?.call(imageUrls[imageIndex]);
                    },
                  ),
                ),
              ),
              ksizeVerticalExtraSmall,
              _ArtistProfile(artist: artist),
            ],
          );
        },
      ),
    );
  }
}
```

**Comment by danPyk** [comment]
Whoops, thanks for clarify.
