### ISSUE TITLE
[feature]: Add `rebuildUi` to `ListenableServiceMixin`

### ISSUE THREAD

**Issue by sebastianbuechler** [Stacked-Org/stacked#998]
### Is your feature request related to a problem? Please describe.

In the "ViewModel-World" there was a wording change from calling natively `notifyListeners` to `rebuildUi`. But when working with services this new terminology is missing and we still need to use the `notifyListeners` command:

![image](https://github.com/Stacked-Org/stacked/assets/42775578/d7fd3160-6241-44f1-b1f6-9ad449344839)

### Describe the solution you would like

Add a wrapper function `rebuildUi` to the `ListenableServiceMixin` mixin so that we have access to the same terminology in the service layer as well.

**Comment by FilledStacks** [comment]
@sebastianbuechler this was intentional. The reason being:

1. The service is a `Listenable`ServiceMixin, so notifying the `Listeners` make sense here
2. The reactive service is not always used for `rebuildingUI`, although that is the primary use case. We also use it to listen to services and react to their state changes in other services by adding a listener to that service. 

For that reason we decided to keep it as `notifyListeners`

Does that make sense? 

Is there anything we can do to make it clearer?

**Comment by sebastianbuechler** [comment]
@FilledStacks With that context it makes complete sense. I just did not come across a case, where I did not want to update the UI when the service had to notify its listeners, but that's highly depending on the type of app you're building I guess. 

No, I don't think there's another option to make it clearer.
